swagger: "2.0"
info:
  version: "0.9.0"
  title: Insights Server
  description: feeds frontend for movie character insights app
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:

  /movies:
    x-swagger-router-controller: moviesController
    get:
      operationId: getAllMoviesRequest
      summary: Movie Scripts List
      description: |
        Returns a list of all available movie scripts.
      tags:
        - Movies
      responses:
        200:
          description: An array of movie scripts
          schema:
            type: array
            items: 
              $ref: '#/definitions/BasicMovie'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  /movies/{id}:
    x-swagger-router-controller: moviesController
    get:
      operationId: getMovieRequest
      summary: All information regarding one movie
      description: |
        Returns all specific data available for one movie: meta information and all available characters.
      parameters:
        - name: id
          in: path
          type: string
          required: true
          description: The id of the movie.
      tags:
        - Movies
      responses:
        200:
          description: A movie script object
          schema:
            $ref: '#/definitions/DetailedMovie'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /characters:
    x-swagger-router-controller: characterController
    get: 
      operationId: getAllCharactersRequest
      description: |
        Return a list of all available movie characters
      tags:
        - Characters
      responses:
        200:
          description: An array of characters
          schema:
            type: array
            items: 
              $ref: '#/definitions/BasicCharacter'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'  

  /characters/{id}:
    x-swagger-router-controller: characterController
    get:
      operationId: getCharacterRequest
      summary: All information regarding one movie character
      description: |
        Returns all specific data available for one movie character: meta information and all available character insight information.
      parameters:
        - name: id
          in: path
          type: string
          required: true
          description: The id of the movie character.
      tags:
        - Characters
      responses:
        200:
          description: A movie character object
          schema:
            $ref: '#/definitions/DetailedCharacter'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error' 
                 
  /quiz/question:
    x-swagger-router-controller: quizController
    post:
      operationId: getQuiz
      summary: Informations for a new quiz
      description: Returns a new quiz for the specified movies and character
      parameters:
        - name: quizRequest
          in: body
          required: true
          description: The movies for which the quiz should be generated
          schema:
            $ref: '#/definitions/QuizRequest'
      tags:
        - Quiz
      responses:
        200: 
          description: A question object
          schema: 
            $ref: '#/definitions/Question'
        default:
          description: Unexpected Error
          schema:
            $ref: '#/definitions/Error'

  /quiz/result:
    x-swagger-router-controller: quizController
    post:
      operationId: postResults
      summary: Result for a finished quiz
      description: Contains the result for a finished quiz with all information about items
      parameters:
        - name: quizResult
          in: body
          required: true
          description: The result as an object
          schema:
            $ref: '#/definitions/QuizResult'
      tags:
        - Quiz
      responses:
        default:
          description: Unexpected Error
          schema:
            $ref: '#/definitions/Error'
            
  /upload:
    x-swagger-router-controller: uploadController
    post:
      operationId: textUpload
      summary: Uploads text and returns insight values
      description: Uploads text from the user and returns the insight values generated by the bluemix services
      parameters:
        - name: text
          in: body
          required: true
          description: Text from the user
          schema:
            $ref: '#/definitions/Text'
      tags:
        - Upload
      responses:
        200:
          description: Insight object which was generated from the user text
          schema:
            $ref: '#/definitions/Insight'
        500:
          description: Internal server error (e.g. text not suitable for watson, detailed description in the response)
          schema:
            $ref: '#/definitions/Error'
  
  /search:
    x-swagger-router-controller: searchController
    post:
      operationId: search
      summary: Search for similar characters
      description: Uses an uploaded insights object to find the the most similar characters in specific dimensions
      parameters:
        - name: search
          in: body
          required: true
          description: Search object
          schema: 
            $ref: '#/definitions/Search'
      tags:
        - Search
      responses:
        200:
          description: An insights object with characters instead of insight values
          schema:
            $ref: '#/definitions/SearchResult'
        default:
          description: Unexpected Error
          schema:
            $ref: '#/definitions/Error'

  /swagger:
    x-swagger-pipe: swagger_raw
    
# complex objects have schema definitions
definitions:
  Names:
    type: object
    properties:
      scriptUnified:
        type: string
        description: Alphabetically better version of the name
      resolved:
        type: string
        description: Name of the movie
  
  Picture:
    type: object
    properties:
      path: 
        type: string
        description: File path to picture.
      source: 
        type: string
        description: Source URL of picture (where downloaded).
      license:
        type: string
        description: License information.

  BasicMovie:
    type: object
    properties:
      _id:
        type: string
        description: Unique identifier representing a specific movie script.
      names:
         $ref: '#/definitions/Names'
      picture: 
         $ref: '#/definitions/Picture'
      unifiedScore:
        type: number
        format: float
        description: combined score of imdbScore and imdbRatingAmount
        
  DetailedMovie:
    type: object
    properties:
      _id:
        type: string
        description: Unique identifier representing a specific movie script.
      names:
         $ref: '#/definitions/Names'
      plot:
        type: string
        description: Movie plot
      year:
        type: integer
        format: int32
        description: Year when the movie was published.
      picture: 
         $ref: '#/definitions/Picture'
      imdbScore:
        type: number
        format: float
        description: imdb movie score
      imdbRatingAmount:
        type: integer
        description: amount of imdb ratings for this movie
      unifiedScore:
        type: number
        format: float
        description: combined score of imdbScore and imdbRatingAmount
      duration:
        type: integer
        format: int32
        description: Duration of movie in minutes.
      genres:
        type: array
        description: array of genres
        items:
          type: string
      director:
        type: string
        description: Name of movie director.
      characters:
        type: array
        items:
          $ref: '#/definitions/BasicCharacter'
        
  BasicCharacter:
    type: object
    description: Short information about one character that appeared in a movie.
    properties:
      _id:
        type: string
        description: Unique identifier representing a specific movie character.
      name:
        type: string
        description: Full name of the character.
      picture: 
        $ref: '#/definitions/Picture'
        
  DetailedCharacter:
    type: object
    properties:
      _id:
        type: string
        description: Unique identifier representing a specific movie character.
      names:
        type: object
        properties:
          resolved:
            type: string
          scriptUnified:
            type: string
        description: Full name of the character.
      description:
        type: object
        description: Information about the character.
        properties:
          paragraphs:
            type: array
            items:
                type: string
            description: Description text for character.
          source:
            type: string
            description: Source URL of description text.
      picture: 
        $ref: '#/definitions/Picture'      
      actor:
        type: string
        description: Name of the actor who played this character.
      insight:
        $ref: '#/definitions/Insight'
  
  Search:
    type: object
    description: Search query containing an array of movie ids and a insights object
    properties:
      movies:
        type: array
        description: array of movie ids
        items:
          type: string
      character:
        type: object
        properties:
          _id: 
            type: string
            description: id of a movie character
          insight:
            $ref: '#/definitions/Insight'
  
  SearchResult:
    type: array
    description: Search result for the provided insight object.
    items:
      $ref: '#/definitions/SearchInsightDimension'
          
  SearchInsightDimension:
    type: object
    description: Object that contains the dimension id and the resulting characters
    properties:
      dimensions:
        type: array
        description: Array which contains the ids of the dimension and subdimension 
        items: 
          type: string
          description: dimension id
          
      characters:
        type: array
        items:
          type: string
          description: character id
        
  Insight:
    type: object
    description: All personality insights values retrieved from IBM Watson service.
    properties:
      personality:
        type: array
        description: array of personality values according to Big 5 Dimensions
        items: 
          $ref: '#/definitions/InsightDimension'
      values:
        type: array
        description: array of personality value numbers
        items: 
          $ref: '#/definitions/InsightValueObject'
      needs:
        type: array
        description: array of personality needs numbers
        items: 
          $ref: '#/definitions/InsightValueObject'

  InsightDimension:
    type: object
    description: one personality value including subdimension values
    properties:
      _id:
        type: string
        description: personality dimension id
      name:
        type: string
        description: personality dimension name
      score:
        type: number
        format: float
        description: personality dimension score
      normalizedScore:
        type: number
        format: float
        description: normalized personality dimension score
      samplingError:
        type: number
        format: float
        description: personality dimension sampling error
      normalizedSamplingError:
        type: number
        format: float
        description: normalized personality dimension sampling error
      subDimensions:
        type: array
        description: array of subdimensions
        items:
          $ref: '#/definitions/InsightValueObject'
          
  InsightValueObject:
    type: object
    description: personality information for one value (personality subdimension, value or need)
    properties:
      _id:
        type: string
        description: personality subdimension id
      name:
        type: string
        description: personality subdimension name
      score:
        type: number
        format: float
        description: personality subdimension score
      normalizedScore:
        type: number
        format: float
        description: normalized personality dimension score
      samplingError:
        type: number
        format: float
        description: personality subdimension sampling error        
   
  QuizRequest:
    type: object
    description: object which contains all necessary information to fullfill the request
    properties: 
      movies:
        type: array
        description: array of movie ids
        items:
          type: string
      excludedCharacters: 
        type: array
        description: array of character ids
        items: 
          type: string
      quizType:
        type: integer
        description: 1 for dimension quiz, 0 for subdimension quiz
             
  Similarity:
    type: object
    properties:
      _id:
        type: string
        description: id of the character
      similarity:
        type: number
        format: float
        description: similarity score of the character

  Question:
    type: object
    description: object which contains the referenceCharacter the distractorCharacters and the similarCharacter
    properties:
      referenceCharacter:
        $ref: '#/definitions/Similarity'
      distractorCharacters:
        type: array
        items:
           $ref: '#/definitions/Similarity'
      similarCharacter:
        $ref: '#/definitions/Similarity'
      dimension:
        type: string
        description: Name of the Dimension or Subdimension
      quizType:
        type: integer
        description: 1 for dimension quiz, 0 for subdimension quiz 

  QuizResult:
    type: object
    description: object which contains all information about the result of a quiz
    properties:
      questions: 
        type: array
        description: an array of questions
        items:
          $ref: '#/definitions/Answer'
      ip: 
        type: string
        description: ip of the user
      end: 
        type: string 
        description: timestamp of the end of the quiz
      creationTime:
        type: string 
        description: server timestamp

  Answer:
    type: object
    description: object which contains the referenceCharacter the distractorCharacters and the similarCharacter
    properties:
      referenceCharacter:
        $ref: '#/definitions/Similarity'
      distractorCharacters:
        type: array
        items:
           $ref: '#/definitions/Similarity'
      similarCharacter:
        $ref: '#/definitions/Similarity'
      answer:
        type: string
      timeTaken: 
        type: string
      quizType:
        type: integer
        description: 1 for dimension quiz, 0 for subdimension quiz 
      dimension:
        type: string
        description: dimension the quiz was about

  
  Text: 
    type: object
    description: Object which contains the text from the user
    properties:
      text: 
        type: string
        description: Text from the user

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
