/**
 * Insights Server
 * feeds frontend for movie character insights app
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BasicMovie', 'model/Error', 'model/DetailedMovie'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient.js'), require('../model/BasicMovie.js'), require('../model/Error.js'), require('../model/DetailedMovie.js'));
  } else {
    // Browser globals (root is window)
    if (!root.InsightsServer) {
      root.InsightsServer = {};
    }
    root.InsightsServer.MoviesApi = factory(root.InsightsServer.ApiClient, root.InsightsServer.BasicMovie, root.InsightsServer.Error, root.InsightsServer.DetailedMovie);
  }
}(this, function(ApiClient, BasicMovie, Error, DetailedMovie) {
  'use strict';

  /**
   * Movies service.
   * @module api/MoviesApi
   * @version 0.9.0
   */

  /**
   * Constructs a new MoviesApi. 
   * @alias module:api/MoviesApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getAllMoviesRequest operation.
     * @callback module:api/MoviesApi~getAllMoviesRequestCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/BasicMovie>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Movie Scripts List
     * Returns a list of all available movie scripts. 
     * @param {module:api/MoviesApi~getAllMoviesRequestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/BasicMovie>}
     */
    this.getAllMoviesRequest = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [BasicMovie];

      return this.apiClient.callApi(
        '/movies', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getMovieRequest operation.
     * @callback module:api/MoviesApi~getMovieRequestCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DetailedMovie} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * All information regarding one movie
     * Returns all specific data available for one movie: meta information and all available characters. 
     * @param {String} id The id of the movie.
     * @param {module:api/MoviesApi~getMovieRequestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DetailedMovie}
     */
    this.getMovieRequest = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling getMovieRequest";
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = DetailedMovie;

      return this.apiClient.callApi(
        '/movies/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
