/**
 * Insights Server
 * feeds frontend for movie character insights app
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Insight', 'model/Error', 'model/Text'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient.js'), require('../model/Insight.js'), require('../model/Error.js'), require('../model/Text.js'));
  } else {
    // Browser globals (root is window)
    if (!root.InsightsServer) {
      root.InsightsServer = {};
    }
    root.InsightsServer.UploadApi = factory(root.InsightsServer.ApiClient, root.InsightsServer.Insight, root.InsightsServer.Error, root.InsightsServer.Text);
  }
}(this, function(ApiClient, Insight, Error, Text) {
  'use strict';

  /**
   * Upload service.
   * @module api/UploadApi
   * @version 0.9.0
   */

  /**
   * Constructs a new UploadApi. 
   * @alias module:api/UploadApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the textUpload operation.
     * @callback module:api/UploadApi~textUploadCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Insight} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Uploads text and returns insight values
     * Uploads text from the user and returns the insight values generated by the bluemix services
     * @param {module:model/Text} text Text from the user
     * @param {module:api/UploadApi~textUploadCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Insight}
     */
    this.textUpload = function(text, callback) {
      var postBody = text;

      // verify the required parameter 'text' is set
      if (text == undefined || text == null) {
        throw "Missing the required parameter 'text' when calling textUpload";
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Insight;

      return this.apiClient.callApi(
        '/upload', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
