// UI
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const SHOW_LIST_AS_LIST = 'SHOW_LIST_AS_LIST';
export const SHOW_LIST_AS_GRID = 'SHOW_LIST_AS_GRID';
export const CHANGE_ITEMS_PER_PAGE = 'CHANGE_ITEMS_PER_PAGE';
export const SET_MOVIES_PAGE = 'SET_MOVIE_PAGE';
export const SET_CHARACTERS_PAGE = 'SET_CHARACTERS_PAGE';

// MOVIES
// Movie list actions
export const INVALIDATE_MOVIES = 'INVALIDATE_MOVIES';
export const REQUEST_MOVIES = 'REQUEST_MOVIES';
export const RECEIVE_MOVIES = 'RECEIVE_MOVIES';
export const FAILED_MOVIES = 'FAILED_MOVIES';
// Selected movie actions
export const SELECT_MOVIE = 'SELECT_MOVIE';
export const INVALIDATE_MOVIE_DETAILS = 'INVALIDATE_MOVIE_DETAILS';
export const REQUEST_MOVIE_DETAILS = 'REQUEST_MOVIE_DETAILS';
export const RECEIVE_MOVIE_DETAILS = 'RECEIVE_MOVIE_DETAILS';
export const FAILED_MOVIE_DETAILS = 'FAILED_MOVIE_DETAILS';

// CHARACTERS
// Character list actions
export const INVALIDATE_CHARACTERS = 'INVALIDATE_CHARACTERS';
export const REQUEST_CHARACTERS = 'REQUEST_CHARACTERS';
export const RECEIVE_CHARACTERS = 'RECEIVE_CHARACTERS';
export const FAILED_CHARACTERS = 'FAILED_CHARACTERS';
// Selected character actions
export const SELECT_CHARACTER = 'SELECT_CHARACTER';
export const INVALIDATE_CHARATER_DETAILS = 'INVALIDATE_CHARATER_DETAILS';
export const REQUEST_CHARACTER_DETAILS = 'REQUEST_CHARACTER_DETAILS';
export const RECEIVE_CHARACTER_DETAILS = 'RECEIVE_CHARACTER_DETAILS';
export const FAILED_CHARACTER_DETAILS = 'FAILED_CHARACTER_DETAILS';

// QUIZ
// Prepare quiz
export const SELECT_QUIZ_MOVIE = 'SELECT_QUIZ_MOVIE';
export const DESELECT_QUIZ_MOVIE = 'DESELECT_QUIZ_MOVIE';
export const DISCARD_QUIZ_MOVIE = 'DISCARD_QUIZ_MOVIE';
export const LOAD_SELECTABLE_MOVIES = 'LOAD_SELECTABLE_MOVIES';
export const START_QUIZ = 'START_QUIZ';
// Quiz in progress
export const PICK_ANSWER = 'PICK_ANSWER';
export const REQUEST_QUESTION = 'REQUEST_QUESTION';
export const RECEIVE_QUESTION = 'RECEIVE_QUESTION';
export const FAILED_QUESTION = 'FAILED_QUESTION';
export const CHARACTER_DETAILS_REQUESTED = 'CHARACTER_DETAILS_REQUESTED';
export const QUESTION_FINISHED = 'QUESTION_FINISHED';
// Quiz finished
export const RESET_QUIZ = 'RESET_QUIZ';
export const SAVE_QUIZ = 'SAVE_QUIZ';
export const SAVE_QUIZ_SUCCESS = 'SAVE_QUIZ_SUCCESS';
export const SAVE_QUIZ_FAILURE = 'SAVE_QUIZ_FAILURE';

// SEARCH
export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const SEARCH_MOVIE_QUERY_CHANGED = 'SEARCH_MOVIE_QUERY_CHANGED';
export const SEARCH_MOVIE_RESET = 'SEARCH_MOVIE_RESET';
export const SEARCH_CHARACTER = 'SEARCH_CHARACTER';
export const SEARCH_CHARACTER_RESET = 'SEARCH_CHARACTER_RESET';
export const SEARCH_CHARACTER_QUERY_CHANGED = 'SEARCH_CHARACTER_QUERY_CHANGED';

// COMPARISON
export const ADD_COMPARISON_CHARACTER = 'ADD_COMPARISON_CHARACTER';
export const REMOVE_COMPARISON_CHARACTER = 'REMOVE_COMPARISON_CHARACTER';
export const CLEAR_COMPARISON_CHARACTERS = 'CLEAR_COMPARISON_CHARACTERS';

// TEXT UPLOAD
export const REQUEST_TEXT_UPLOAD = 'REQUEST_TEXT_UPLOAD';
export const RECEIVE_TEXT_UPLOAD = 'RECEIVE_TEXT_UPLOAD';
export const FAILED_TEXT_UPLOAD = 'FAILED_TEXT_UPLOAD';
export const RESET_UPLOAD_TEXT = 'RESET_UPLOAD_TEXT';

// SEARCH
export const SELECT_REFERENCE_CHARACTER = 'SELECT_REFERENCE_CHARACTER';
export const REQUEST_SEARCH_RESULT = 'REQUEST_SEARCH_RESULT';
export const RECEIVE_SEARCH_RESULT = 'RECEIVE_SEARCH_RESULT';
export const FAILED_SEARCH_RESULT = 'FAILED_SEARCH_RESULT';
