/**
 * Insights Server
 * feeds frontend for movie character insights app
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DetailedCharacterDescription', 'model/DetailedCharacterNames', 'model/Insight', 'model/Picture'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient.js'), require('./DetailedCharacterDescription.js'), require('./DetailedCharacterNames.js'), require('./Insight.js'), require('./Picture.js'));
  } else {
    // Browser globals (root is window)
    if (!root.InsightsServer) {
      root.InsightsServer = {};
    }
    root.InsightsServer.DetailedCharacter = factory(root.InsightsServer.ApiClient, root.InsightsServer.DetailedCharacterDescription, root.InsightsServer.DetailedCharacterNames, root.InsightsServer.Insight, root.InsightsServer.Picture);
  }
}(this, function(ApiClient, DetailedCharacterDescription, DetailedCharacterNames, Insight, Picture) {
  'use strict';




  /**
   * The DetailedCharacter model module.
   * @module model/DetailedCharacter
   * @version 0.9.0
   */

  /**
   * Constructs a new <code>DetailedCharacter</code>.
   * @alias module:model/DetailedCharacter
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>DetailedCharacter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DetailedCharacter} obj Optional instance to populate.
   * @return {module:model/DetailedCharacter} The populated <code>DetailedCharacter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('_id')) {
        obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
      }
      if (data.hasOwnProperty('names')) {
        obj['names'] = DetailedCharacterNames.constructFromObject(data['names']);
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = DetailedCharacterDescription.constructFromObject(data['description']);
      }
      if (data.hasOwnProperty('picture')) {
        obj['picture'] = Picture.constructFromObject(data['picture']);
      }
      if (data.hasOwnProperty('actor')) {
        obj['actor'] = ApiClient.convertToType(data['actor'], 'String');
      }
      if (data.hasOwnProperty('insight')) {
        obj['insight'] = Insight.constructFromObject(data['insight']);
      }
    }
    return obj;
  }

  /**
   * Unique identifier representing a specific movie character.
   * @member {String} _id
   */
  exports.prototype['_id'] = undefined;
  /**
   * @member {module:model/DetailedCharacterNames} names
   */
  exports.prototype['names'] = undefined;
  /**
   * @member {module:model/DetailedCharacterDescription} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {module:model/Picture} picture
   */
  exports.prototype['picture'] = undefined;
  /**
   * Name of the actor who played this character.
   * @member {String} actor
   */
  exports.prototype['actor'] = undefined;
  /**
   * @member {module:model/Insight} insight
   */
  exports.prototype['insight'] = undefined;



  return exports;
}));


