/**
 * Insights Server
 * feeds frontend for movie character insights app
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InsightValueObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient.js'), require('./InsightValueObject.js'));
  } else {
    // Browser globals (root is window)
    if (!root.InsightsServer) {
      root.InsightsServer = {};
    }
    root.InsightsServer.InsightDimension = factory(root.InsightsServer.ApiClient, root.InsightsServer.InsightValueObject);
  }
}(this, function(ApiClient, InsightValueObject) {
  'use strict';




  /**
   * The InsightDimension model module.
   * @module model/InsightDimension
   * @version 0.9.0
   */

  /**
   * Constructs a new <code>InsightDimension</code>.
   * one personality value including subdimension values
   * @alias module:model/InsightDimension
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>InsightDimension</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InsightDimension} obj Optional instance to populate.
   * @return {module:model/InsightDimension} The populated <code>InsightDimension</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('_id')) {
        obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('score')) {
        obj['score'] = ApiClient.convertToType(data['score'], 'Number');
      }
      if (data.hasOwnProperty('normalizedScore')) {
        obj['normalizedScore'] = ApiClient.convertToType(data['normalizedScore'], 'Number');
      }
      if (data.hasOwnProperty('samplingError')) {
        obj['samplingError'] = ApiClient.convertToType(data['samplingError'], 'Number');
      }
      if (data.hasOwnProperty('normalizedSamplingError')) {
        obj['normalizedSamplingError'] = ApiClient.convertToType(data['normalizedSamplingError'], 'Number');
      }
      if (data.hasOwnProperty('subDimensions')) {
        obj['subDimensions'] = ApiClient.convertToType(data['subDimensions'], [InsightValueObject]);
      }
    }
    return obj;
  }

  /**
   * personality dimension id
   * @member {String} _id
   */
  exports.prototype['_id'] = undefined;
  /**
   * personality dimension name
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * personality dimension score
   * @member {Number} score
   */
  exports.prototype['score'] = undefined;
  /**
   * normalized personality dimension score
   * @member {Number} normalizedScore
   */
  exports.prototype['normalizedScore'] = undefined;
  /**
   * personality dimension sampling error
   * @member {Number} samplingError
   */
  exports.prototype['samplingError'] = undefined;
  /**
   * normalized personality dimension sampling error
   * @member {Number} normalizedSamplingError
   */
  exports.prototype['normalizedSamplingError'] = undefined;
  /**
   * array of subdimensions
   * @member {Array.<module:model/InsightValueObject>} subDimensions
   */
  exports.prototype['subDimensions'] = undefined;



  return exports;
}));


