/**
 * Insights Server
 * feeds frontend for movie character insights app
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InsightDimension', 'model/InsightValueObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient.js'), require('./InsightDimension.js'), require('./InsightValueObject.js'));
  } else {
    // Browser globals (root is window)
    if (!root.InsightsServer) {
      root.InsightsServer = {};
    }
    root.InsightsServer.Insight = factory(root.InsightsServer.ApiClient, root.InsightsServer.InsightDimension, root.InsightsServer.InsightValueObject);
  }
}(this, function(ApiClient, InsightDimension, InsightValueObject) {
  'use strict';




  /**
   * The Insight model module.
   * @module model/Insight
   * @version 0.9.0
   */

  /**
   * Constructs a new <code>Insight</code>.
   * All personality insights values retrieved from IBM Watson service.
   * @alias module:model/Insight
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Insight</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Insight} obj Optional instance to populate.
   * @return {module:model/Insight} The populated <code>Insight</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('personality')) {
        obj['personality'] = ApiClient.convertToType(data['personality'], [InsightDimension]);
      }
      if (data.hasOwnProperty('values')) {
        obj['values'] = ApiClient.convertToType(data['values'], [InsightValueObject]);
      }
      if (data.hasOwnProperty('needs')) {
        obj['needs'] = ApiClient.convertToType(data['needs'], [InsightValueObject]);
      }
    }
    return obj;
  }

  /**
   * array of personality values according to Big 5 Dimensions
   * @member {Array.<module:model/InsightDimension>} personality
   */
  exports.prototype['personality'] = undefined;
  /**
   * array of personality value numbers
   * @member {Array.<module:model/InsightValueObject>} values
   */
  exports.prototype['values'] = undefined;
  /**
   * array of personality needs numbers
   * @member {Array.<module:model/InsightValueObject>} needs
   */
  exports.prototype['needs'] = undefined;



  return exports;
}));


