/**
 * Insights Server
 * feeds frontend for movie character insights app
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Similarity'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient.js'), require('./Similarity.js'));
  } else {
    // Browser globals (root is window)
    if (!root.InsightsServer) {
      root.InsightsServer = {};
    }
    root.InsightsServer.Question = factory(root.InsightsServer.ApiClient, root.InsightsServer.Similarity);
  }
}(this, function(ApiClient, Similarity) {
  'use strict';




  /**
   * The Question model module.
   * @module model/Question
   * @version 0.9.0
   */

  /**
   * Constructs a new <code>Question</code>.
   * object which contains the referenceCharacter the distractorCharacters and the similarCharacter
   * @alias module:model/Question
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>Question</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Question} obj Optional instance to populate.
   * @return {module:model/Question} The populated <code>Question</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('referenceCharacter')) {
        obj['referenceCharacter'] = Similarity.constructFromObject(data['referenceCharacter']);
      }
      if (data.hasOwnProperty('distractorCharacters')) {
        obj['distractorCharacters'] = ApiClient.convertToType(data['distractorCharacters'], [Similarity]);
      }
      if (data.hasOwnProperty('similarCharacter')) {
        obj['similarCharacter'] = Similarity.constructFromObject(data['similarCharacter']);
      }
      if (data.hasOwnProperty('dimension')) {
        obj['dimension'] = ApiClient.convertToType(data['dimension'], 'String');
      }
      if (data.hasOwnProperty('quizType')) {
        obj['quizType'] = ApiClient.convertToType(data['quizType'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Similarity} referenceCharacter
   */
  exports.prototype['referenceCharacter'] = undefined;
  /**
   * @member {Array.<module:model/Similarity>} distractorCharacters
   */
  exports.prototype['distractorCharacters'] = undefined;
  /**
   * @member {module:model/Similarity} similarCharacter
   */
  exports.prototype['similarCharacter'] = undefined;
  /**
   * Name of the Dimension or Subdimension
   * @member {String} dimension
   */
  exports.prototype['dimension'] = undefined;
  /**
   * 1 for dimension quiz, 0 for subdimension quiz
   * @member {Integer} quizType
   */
  exports.prototype['quizType'] = undefined;



  return exports;
}));


