/**
 * Insights Server
 * feeds frontend for movie character insights app
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient.js'));
  } else {
    // Browser globals (root is window)
    if (!root.InsightsServer) {
      root.InsightsServer = {};
    }
    root.InsightsServer.QuizRequest = factory(root.InsightsServer.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The QuizRequest model module.
   * @module model/QuizRequest
   * @version 0.9.0
   */

  /**
   * Constructs a new <code>QuizRequest</code>.
   * object which contains all necessary information to fullfill the request
   * @alias module:model/QuizRequest
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>QuizRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QuizRequest} obj Optional instance to populate.
   * @return {module:model/QuizRequest} The populated <code>QuizRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('movies')) {
        obj['movies'] = ApiClient.convertToType(data['movies'], ['String']);
      }
      if (data.hasOwnProperty('excludedCharacters')) {
        obj['excludedCharacters'] = ApiClient.convertToType(data['excludedCharacters'], ['String']);
      }
      if (data.hasOwnProperty('quizType')) {
        obj['quizType'] = ApiClient.convertToType(data['quizType'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * array of movie ids
   * @member {Array.<String>} movies
   */
  exports.prototype['movies'] = undefined;
  /**
   * array of character ids
   * @member {Array.<String>} excludedCharacters
   */
  exports.prototype['excludedCharacters'] = undefined;
  /**
   * 1 for dimension quiz, 0 for subdimension quiz
   * @member {Integer} quizType
   */
  exports.prototype['quizType'] = undefined;



  return exports;
}));


