/**
 * Insights Server
 * feeds frontend for movie character insights app
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Insight'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient.js'), require('./Insight.js'));
  } else {
    // Browser globals (root is window)
    if (!root.InsightsServer) {
      root.InsightsServer = {};
    }
    root.InsightsServer.SearchCharacter = factory(root.InsightsServer.ApiClient, root.InsightsServer.Insight);
  }
}(this, function(ApiClient, Insight) {
  'use strict';




  /**
   * The SearchCharacter model module.
   * @module model/SearchCharacter
   * @version 0.9.0
   */

  /**
   * Constructs a new <code>SearchCharacter</code>.
   * @alias module:model/SearchCharacter
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>SearchCharacter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchCharacter} obj Optional instance to populate.
   * @return {module:model/SearchCharacter} The populated <code>SearchCharacter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('_id')) {
        obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
      }
      if (data.hasOwnProperty('insight')) {
        obj['insight'] = Insight.constructFromObject(data['insight']);
      }
    }
    return obj;
  }

  /**
   * id of a movie character
   * @member {String} _id
   */
  exports.prototype['_id'] = undefined;
  /**
   * @member {module:model/Insight} insight
   */
  exports.prototype['insight'] = undefined;



  return exports;
}));


