/**
 * Insights Server
 * feeds frontend for movie character insights app
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient.js'));
  } else {
    // Browser globals (root is window)
    if (!root.InsightsServer) {
      root.InsightsServer = {};
    }
    root.InsightsServer.SearchInsightDimension = factory(root.InsightsServer.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SearchInsightDimension model module.
   * @module model/SearchInsightDimension
   * @version 0.9.0
   */

  /**
   * Constructs a new <code>SearchInsightDimension</code>.
   * Object that contains the dimension id and the resulting characters
   * @alias module:model/SearchInsightDimension
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>SearchInsightDimension</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchInsightDimension} obj Optional instance to populate.
   * @return {module:model/SearchInsightDimension} The populated <code>SearchInsightDimension</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('dimensions')) {
        obj['dimensions'] = ApiClient.convertToType(data['dimensions'], ['String']);
      }
      if (data.hasOwnProperty('characters')) {
        obj['characters'] = ApiClient.convertToType(data['characters'], ['String']);
      }
    }
    return obj;
  }

  /**
   * Array which contains the ids of the dimension and subdimension
   * @member {Array.<String>} dimensions
   */
  exports.prototype['dimensions'] = undefined;
  /**
   * @member {Array.<String>} characters
   */
  exports.prototype['characters'] = undefined;



  return exports;
}));


