/**
 * Insights Server
 * feeds frontend for movie character insights app
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (false) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BasicCharacter'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient.js'), require('./BasicCharacter.js'));
  } else {
    // Browser globals (root is window)
    if (!root.InsightsServer) {
      root.InsightsServer = {};
    }
    root.InsightsServer.SearchInsightValueObject = factory(root.InsightsServer.ApiClient, root.InsightsServer.BasicCharacter);
  }
}(this, function(ApiClient, BasicCharacter) {
  'use strict';




  /**
   * The SearchInsightValueObject model module.
   * @module model/SearchInsightValueObject
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>SearchInsightValueObject</code>.
   * personality information for one value (personality subdimension, value or need)
   * @alias module:model/SearchInsightValueObject
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>SearchInsightValueObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchInsightValueObject} obj Optional instance to populate.
   * @return {module:model/SearchInsightValueObject} The populated <code>SearchInsightValueObject</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('_id')) {
        obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('characters')) {
        obj['characters'] = ApiClient.convertToType(data['characters'], [BasicCharacter]);
      }
    }
    return obj;
  }

  /**
   * personality subdimension id
   * @member {String} _id
   */
  exports.prototype['_id'] = undefined;
  /**
   * personality subdimension name
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Array of the best characters
   * @member {Array.<module:model/BasicCharacter>} characters
   */
  exports.prototype['characters'] = undefined;



  return exports;
}));


