/**
 * Insights Server
 * feeds frontend for movie character insights app
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (false) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InsightsServer);
  }
}(this, function(expect, InsightsServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InsightsServer.DetailedMovie();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DetailedMovie', function() {
    it('should create an instance of DetailedMovie', function() {
      // uncomment below and update the code to test DetailedMovie
      //var instane = new InsightsServer.DetailedMovie();
      //expect(instance).to.be.a(InsightsServer.DetailedMovie);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new InsightsServer.DetailedMovie();
      //expect(instance).to.be();
    });

    it('should have the property names (base name: "names")', function() {
      // uncomment below and update the code to test the property names
      //var instane = new InsightsServer.DetailedMovie();
      //expect(instance).to.be();
    });

    it('should have the property plot (base name: "plot")', function() {
      // uncomment below and update the code to test the property plot
      //var instane = new InsightsServer.DetailedMovie();
      //expect(instance).to.be();
    });

    it('should have the property year (base name: "year")', function() {
      // uncomment below and update the code to test the property year
      //var instane = new InsightsServer.DetailedMovie();
      //expect(instance).to.be();
    });

    it('should have the property picture (base name: "picture")', function() {
      // uncomment below and update the code to test the property picture
      //var instane = new InsightsServer.DetailedMovie();
      //expect(instance).to.be();
    });

    it('should have the property imdbScore (base name: "imdbScore")', function() {
      // uncomment below and update the code to test the property imdbScore
      //var instane = new InsightsServer.DetailedMovie();
      //expect(instance).to.be();
    });

    it('should have the property imdbRatingAmount (base name: "imdbRatingAmount")', function() {
      // uncomment below and update the code to test the property imdbRatingAmount
      //var instane = new InsightsServer.DetailedMovie();
      //expect(instance).to.be();
    });

    it('should have the property unifiedScore (base name: "unifiedScore")', function() {
      // uncomment below and update the code to test the property unifiedScore
      //var instane = new InsightsServer.DetailedMovie();
      //expect(instance).to.be();
    });

    it('should have the property duration (base name: "duration")', function() {
      // uncomment below and update the code to test the property duration
      //var instane = new InsightsServer.DetailedMovie();
      //expect(instance).to.be();
    });

    it('should have the property genres (base name: "genres")', function() {
      // uncomment below and update the code to test the property genres
      //var instane = new InsightsServer.DetailedMovie();
      //expect(instance).to.be();
    });

    it('should have the property director (base name: "director")', function() {
      // uncomment below and update the code to test the property director
      //var instane = new InsightsServer.DetailedMovie();
      //expect(instance).to.be();
    });

    it('should have the property characters (base name: "characters")', function() {
      // uncomment below and update the code to test the property characters
      //var instane = new InsightsServer.DetailedMovie();
      //expect(instance).to.be();
    });

  });

}));
