/**
 * Insights Server
 * feeds frontend for movie character insights app
 *
 * OpenAPI spec version: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (false) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InsightsServer);
  }
}(this, function(expect, InsightsServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InsightsServer.InsightValueObject();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InsightValueObject', function() {
    it('should create an instance of InsightValueObject', function() {
      // uncomment below and update the code to test InsightValueObject
      //var instane = new InsightsServer.InsightValueObject();
      //expect(instance).to.be.a(InsightsServer.InsightValueObject);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new InsightsServer.InsightValueObject();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new InsightsServer.InsightValueObject();
      //expect(instance).to.be();
    });

    it('should have the property score (base name: "score")', function() {
      // uncomment below and update the code to test the property score
      //var instane = new InsightsServer.InsightValueObject();
      //expect(instance).to.be();
    });

    it('should have the property normalizedScore (base name: "normalizedScore")', function() {
      // uncomment below and update the code to test the property normalizedScore
      //var instane = new InsightsServer.InsightValueObject();
      //expect(instance).to.be();
    });

    it('should have the property samplingError (base name: "samplingError")', function() {
      // uncomment below and update the code to test the property samplingError
      //var instane = new InsightsServer.InsightValueObject();
      //expect(instance).to.be();
    });

  });

}));
